# Generated by Django 5.2.7 on 2025-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0003_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='Points to award when attending this event. Leave blank to use default (10 points).', null=True),
        ),
    ]
