# Generated by Django 5.2.7 on 2025-11-28 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0004_event_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MANDATORY', 'Mandatory'), ('OPTIONAL', 'Optional')], default='OPTIONAL', help_text='Mandatory events auto-register all organization members and count toward attendance metrics.', max_length=12),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='True if this registration is for a mandatory event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('USER', 'User')], default='USER', max_length=12),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('join_code', models.CharField(help_text='Unique code for users to join this organization', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this announcement belongs to. Leave blank for global announcements.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='pulse.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this event belongs to. Leave blank for global events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pulse.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='pulse.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ORGANIZER', 'Organizer')], default='MEMBER', max_length=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('joined_via', models.CharField(choices=[('CODE', 'Join Code'), ('INVITE', 'Invite Link')], default='CODE', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pulse.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-joined_at',),
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['join_code'], name='pulse_o_join_co_bf96dc_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvite',
            index=models.Index(fields=['token'], name='pulse_o_token_37ad78_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='pulse_o_organiz_06deda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
    ]
