# Generated by Django 5.2.7 on 2025-11-28 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_event_event_type_registration_is_mandatory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_window_end',
            field=models.DateTimeField(blank=True, help_text='End of attendance scanning window. If blank, uses event end time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_window_start',
            field=models.DateTimeField(blank=True, help_text='Start of attendance scanning window. If blank, uses event start time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_time_in',
            field=models.BooleanField(default=True, help_text='Enable time-in (check-in) tracking for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_time_out',
            field=models.BooleanField(default=False, help_text='Enable time-out (check-out) tracking for this event'),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('TIME_IN', 'Time In'), ('TIME_OUT', 'Time Out')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded for this attendance record')),
                ('notes', models.TextField(blank=True, help_text='Optional notes from organizer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='pulse.event')),
                ('organizer', models.ForeignKey(help_text='Organizer who scanned the QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_attendance', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['event', 'user'], name='pulse_a_event_i_d7d4e1_idx'), models.Index(fields=['event', 'user', 'attendance_type'], name='pulse_a_event_i_c936ba_idx'), models.Index(fields=['timestamp'], name='pulse_a_timesta_522faa_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'attendance_type'), name='unique_attendance_type_per_event_user')],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique token for QR code scanning', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_qr_codes', to='pulse.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['token'], name='pulse_q_token_b5af88_idx'), models.Index(fields=['user', 'organization'], name='pulse_q_user_id_5bf173_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
