# Generated by Django 5.2.7 on 2025-11-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0006_event_attendance_window_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enable_time_in',
        ),
        migrations.RemoveField(
            model_name='event',
            name='enable_time_out',
        ),
        migrations.AddField(
            model_name='event',
            name='enable_afternoon_in',
            field=models.BooleanField(default=False, help_text='Enable afternoon time-in (check-in) tracking for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_afternoon_out',
            field=models.BooleanField(default=False, help_text='Enable afternoon time-out (check-out) tracking for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_morning_in',
            field=models.BooleanField(default=True, help_text='Enable morning time-in (check-in) tracking for this event'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_morning_out',
            field=models.BooleanField(default=False, help_text='Enable morning time-out (check-out) tracking for this event'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_type',
            field=models.CharField(choices=[('MORNING_IN', 'Morning Time In'), ('MORNING_OUT', 'Morning Time Out'), ('AFTERNOON_IN', 'Afternoon Time In'), ('AFTERNOON_OUT', 'Afternoon Time Out')], max_length=15),
        ),
    ]
