# Generated by Django 5.2.7 on 2025-11-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0007_remove_event_enable_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='afternoon_in_end',
            field=models.TimeField(blank=True, help_text='End time for afternoon check-in (e.g., 2:00 PM). If blank, uses event start time + 1 hour.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='afternoon_in_start',
            field=models.TimeField(blank=True, help_text='Start time for afternoon check-in (e.g., 1:00 PM). If blank, uses event start time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='afternoon_out_end',
            field=models.TimeField(blank=True, help_text='End time for afternoon check-out (e.g., 6:00 PM). If blank, uses event start time + 1 hour.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='afternoon_out_start',
            field=models.TimeField(blank=True, help_text='Start time for afternoon check-out (e.g., 5:00 PM). If blank, uses event start time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='morning_in_end',
            field=models.TimeField(blank=True, help_text='End time for morning check-in (e.g., 8:30 AM). If blank, uses event start time + 1 hour.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='morning_in_start',
            field=models.TimeField(blank=True, help_text='Start time for morning check-in (e.g., 7:30 AM). If blank, uses event start time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='morning_out_end',
            field=models.TimeField(blank=True, help_text='End time for morning check-out (e.g., 12:00 PM). If blank, uses event start time + 1 hour.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='morning_out_start',
            field=models.TimeField(blank=True, help_text='Start time for morning check-out (e.g., 11:00 AM). If blank, uses event start time.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_window_end',
            field=models.DateTimeField(blank=True, help_text='End of overall attendance scanning window. If blank, uses event end time.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendance_window_start',
            field=models.DateTimeField(blank=True, help_text='Start of overall attendance scanning window. If blank, uses event start time.', null=True),
        ),
    ]
