# Generated by Django 5.2.7 on 2025-11-29 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0008_event_afternoon_in_end_event_afternoon_in_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('MORNING_IN', 'Morning Time In'), ('MORNING_OUT', 'Morning Time Out'), ('AFTERNOON_IN', 'Afternoon Time In'), ('AFTERNOON_OUT', 'Afternoon Time Out'), ('ALL', 'All Attendance Types')], default='ALL', help_text='Which attendance type(s) this excuse applies to', max_length=15)),
                ('reason', models.TextField(help_text='Reason for the excuse request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to='pulse.event')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Organizer who reviewed this excuse', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'user'], name='pulse_e_event_i_705d68_idx'), models.Index(fields=['status'], name='pulse_e_status_0d70db_idx'), models.Index(fields=['-created_at'], name='pulse_e_created_5e904b_idx')],
            },
        ),
    ]
