# Generated by Django 5.2.7 on 2025-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0009_excuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='excuse',
            name='proof_link',
            field=models.URLField(blank=True, help_text='Google Drive link or URL to proof document (medical certificate, excuse letter signed by dean, etc.)', max_length=500),
        ),
    ]
