# Generated by Django 5.2.7 on 2025-11-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0010_excuse_proof_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Notes from the reviewer'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Super admin who reviewed this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Organization approval status', max_length=12),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin')], default='MEMBER', max_length=12),
        ),
    ]
