# Generated by Django 5.2.7 on 2025-11-29 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0012_add_event_date_and_number_of_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-event_date', '-start_datetime')},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, help_text='Date of the event. For multi-day events, create separate events for each day.', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='pulse_e_event_d_ae373d_idx'),
        ),
    ]
