# Generated by Django 5.2.7 on 2025-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0013_alter_event_options_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='pulse_annou_created_477d57_idx',
            old_name='pulse_a_created_128758_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='pulse_atten_event_i_c38c7c_idx',
            old_name='pulse_a_event_i_d7d4e1_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='pulse_atten_event_i_fc88c9_idx',
            old_name='pulse_a_event_i_c936ba_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='pulse_atten_timesta_0847be_idx',
            old_name='pulse_a_timesta_522faa_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='pulse_event_event_d_975a8c_idx',
            old_name='pulse_e_event_d_ae373d_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='pulse_event_start_d_c72f56_idx',
            old_name='pulse_e_start_d_d972bd_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='pulse_event_created_d36084_idx',
            old_name='pulse_e_created_6514c6_idx',
        ),
        migrations.RenameIndex(
            model_name='excuse',
            new_name='pulse_excus_event_i_df790d_idx',
            old_name='pulse_e_event_i_705d68_idx',
        ),
        migrations.RenameIndex(
            model_name='excuse',
            new_name='pulse_excus_status_95cba3_idx',
            old_name='pulse_e_status_0d70db_idx',
        ),
        migrations.RenameIndex(
            model_name='excuse',
            new_name='pulse_excus_created_b0b690_idx',
            old_name='pulse_e_created_5e904b_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='pulse_organ_join_co_15f131_idx',
            old_name='pulse_o_join_co_bf96dc_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='pulse_organ_token_af5479_idx',
            old_name='pulse_o_token_37ad78_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationmembership',
            new_name='pulse_organ_organiz_ccc517_idx',
            old_name='pulse_o_organiz_06deda_idx',
        ),
        migrations.RenameIndex(
            model_name='qrcode',
            new_name='pulse_qrcod_token_8119d1_idx',
            old_name='pulse_q_token_b5af88_idx',
        ),
        migrations.RenameIndex(
            model_name='qrcode',
            new_name='pulse_qrcod_user_id_203392_idx',
            old_name='pulse_q_user_id_5bf173_idx',
        ),
        migrations.RenameIndex(
            model_name='registration',
            new_name='pulse_regis_event_i_560ccc_idx',
            old_name='pulse_r_event_i_cb298d_idx',
        ),
    ]
